serviceId: "cardholder_dropwizard"
serviceName: "cardholder_dropwizard"

server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: root

  # the JDBC URL
  url: jdbc:mysql://localhost/projecttitan

  # any properties specific to your JDBC driver:
  properties:
    #charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.hbm2ddl.auto: update #create
    #hibernate.current_session_context_class: thread